feat: models of the shopping cart, the order, and the order return, c…
Valeriy78/Hillel-Python-Pro pull request #8
Opened 2022-09-19 20:51 UTC by Valeriy78

…orresponding views and templates are implemented

2022-09-29 10:51 UTC, shorodilov requested changes
CRUD з товарами повинен бути доступним лише адміністраторам магазина.
Декоратори для purchase вью застосовані у невідповідному порядку.
Подекуди відсутні перевірки консистентності БД.

2022-09-29 10:51 UTC, shorodilov commented on internet_shop/purchase/forms.py
> +           ('REJECT', 'reject')]
Так краще додавати до відповідного классу

2022-09-29 10:51 UTC, shorodilov commented on internet_shop/purchase/views.py
> +@login_required
Треба перевірити порядок застосування декораторів

2022-09-29 10:51 UTC, shorodilov commented on internet_shop/purchase/views.py
> +        order_return = OrderReturn(customer=customer, order=order)
Не обмежена кількість возвратів для одного заказу, буде валитись у IntegrityError через звʼязок 1-1.

2022-10-03 00:01 UTC, Valeriy78 commented on internet_shop/purchase/forms.py
> +           ('REJECT', 'reject')]
Переніс до класу.

2022-10-03 00:02 UTC, Valeriy78 commented on internet_shop/purchase/views.py
> +@login_required
Змінив порядок декораторів

2022-10-03 00:05 UTC, Valeriy78 commented on internet_shop/purchase/views.py
> +        order_return = OrderReturn(customer=customer, order=order)
Виправив.

2022-11-02 21:10 UTC, shorodilov approved these changes
Completed

2025-04-23 11:55 UTC, merged